apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: dem
  labels:
    app: prometheus
data:
  prometheus.properties: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter'
        scheme: http
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
              - dem
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          regex: 'node-exporter-service'
          action: keep



